# Generated by Django 4.1.7 on 2023-03-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_contact_phone_contact_phones_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Data',
        ),
    ]
